### ISSUE TITLE
Support multiple backends

### ISSUE THREAD

**Issue by ip1981** [zalora/sproxy#73]
Support multiple backends with adding a new option `backends`, e. g.

``` yaml
cookie_domain          : example.com # make optional
cookie_name            : sproxy_foo # make optional
backend_socket         : /tmp/foo.sock # optional default

backends:
    - name: example.net
      socket: ... # or address + port
      cookie_name: foo # optional
    - name: wiki.example.net
      socket: ...
    - name: *.example.org
      socket: ...
  ...
```
